### ISSUE TITLE
.NET Core System.NullReferenceException when hiding strings

### ISSUE THREAD

**Issue by GregFinzer** [lextm/obfuscar#109]
I am receiving the following error when obfuscating a .NET Core Assembly:

d:\Projects\Kellerman\NET-Automated-Builds\NET-Automated-Builds\bin\Debug>Obfuscar.Console.exe Obfuscar.xml
Loading project Obfuscar.xml...Processing assembly: NET-SFTP-Library-Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
Loading assemblies...Extra framework folders: Done.
hiding strings...

Необработанное исключение: System.NullReferenceException: Ссылка на объект не указывает на экземпляр объекта.
   в Obfuscar.Obfuscator.StringSqueeze.Initialize()
   в Obfuscar.Obfuscator.StringSqueeze.ProcessStrings(MethodDefinition method, AssemblyInfo info, Project project)
   в Obfuscar.Obfuscator.HideStrings()
   в Obfuscar.Obfuscator.RunRules()
   в Obfuscar.Program.Main(String[] args)

**Comment by kubakista** [comment]
I get the same error for my "Class Library (Universal Windows)" project.

**Comment by lextm** [comment]
Investigation finished.

The cause is that for .NET Standard assemblies, they don't have a reference to `mscorlib` any more, but `System.Runtime` instead. However, the latter does not make it easy enough to resolve the type of `System.Text.Encoding`. This issue also should apply to UWP assemblies.

Temporarily you have the following workarounds,

* Disable string hiding for such assemblies.
* Merge such assemblies with .NET Framework assemblies (if you do work on a suitable project, like WinForms).

A fix won't easily come as I have no idea now how to fix it.

**Comment by GregFinzer** [comment]
@lextm Thanks so much for the quick investigation.  I will try disabling hiding the strings.

**Comment by kubakista** [comment]
Could you please give me more hints what exactly should be done for UWP assemblies? Maybe example how the config file should look like (roughly).
Thank you.

**Comment by lextm** [comment]
@GregFinzer @kubakista  instead of asking end users like you to manually disable string hiding, now you can upgrade to 2.2.6 release. Obfuscar will automatically skip string hiding when it cannot perform that.

A long term solution would be a separate topic.
