### ISSUE TITLE
Post-build command exited with 9009 error

### ISSUE THREAD

**Issue by fpavlic** [lextm/obfuscar#129]
Hi,

Having trouble running obfuscar on Post-Build. Getting error 9009. When I place "Obfuscar.Console.exe" in project root and run it through command prompt it works, when I try to run same file (in project root) through Post-Build I again get same error.

Any idea?

Here is the build issue.
https://gyazo.com/0a503c8911cc1c629962fc6fa20ff4cb

**Comment by lextm** [comment]
You have to follow the example, https://github.com/lextm/obfuscar_example

**Comment by fpavlic** [comment]
Tried to implement that way.

1) Added NuGet
2) Added Post-Build event "$(Obfuscar) obfuscar.xml"
3) Run project, throws error

When run manual it works fine, anything I'm missing?

**Comment by lextm** [comment]
Check your MSBuild logging, and compare to the standard,

https://ci.appveyor.com/project/lextm/obfuscar-example

As such troubleshooting has nothing to do with Obfuscar itself, but MSBuild and its internals, you will have to do the digging on your own.

**Comment by LukasHandler** [comment]
Hi, I had the same problem. I found an easy solution which I will post here in case anyone else will need it. My output window in visual studio told me: 

"Der Befehl "C:\Users\***\documents\visual" ist entweder falsch geschrieben oder" (The command path was wrong)

So the problem was some spacing in the file path to my source code (...\Visual Studio\...) so all I had to do was edit my PostBuild to this:

**"$(Obfuscar)" obfuscar.xml**

**Comment by ajvico** [comment]
In my case the problem was that this code (in the project file):

```xml
<PropertyGroup>
   <PostBuildEvent>"$(Obfuscar)" obfuscar.xml</PostBuildEvent>
</PropertyGroup>
```
was before this line (mine is VB.NET project):

```xml
<Import Project="$(MSBuildToolsPath)\Microsoft.VisualBasic.targets" />
```

I changed the order of the two fragments of XML code in the project and now it works fine.
