### ISSUE TITLE
the BasicExample obfuscation doen't work and outputs a lot of errors

### ISSUE THREAD

**Issue by jjgh** [lextm/obfuscar#64]
```
\2.0_rc7_src\Obfuscar\..\cecil\Mono.Cecil.csproj" non found
\2.0_rc7_src\Obfuscar\..\cecil\symbols\pdb\Mono.Cecil.Pdb.csproj not found
\2.0_rc7_src\Obfuscar\..\ilspy\ILSpy.BamlDecompiler\CecilDependencyPropertyDescriptor.cs' not found.
\2.0_rc7_src\Obfuscar\..\ilspy\ILSpy.BamlDecompiler\CecilType.cs' not found. 
\2.0_rc7_src\Obfuscar\..\ilspy\ILSpy.BamlDecompiler\CecilTypeResolver.cs' not found. 
\2.0_rc7_src\Obfuscar\..\ilspy\ILSpy.BamlDecompiler\Ricciolo.StylesExplorer.MarkupReflection\BamlBinaryReader.cs' not found.
\2.0_rc7_src\Obfuscar\..\ilspy\ILSpy.BamlDecompiler\Ricciolo.StylesExplorer.MarkupReflection\BamlRecordType.cs' not found.
\2.0_rc7_src\Obfuscar\..\ilspy\ILSpy.BamlDecompiler\Ricciolo.StylesExplorer.MarkupReflection\IDependencyPropertyDescriptor.cs' not found.
\2.0_rc7_src\Obfuscar\..\ilspy\ILSpy.BamlDecompiler\Ricciolo.StylesExplorer.MarkupReflection\IType.cs' not found.
\2.0_rc7_src\Obfuscar\..\ilspy\ILSpy.BamlDecompiler\Ricciolo.StylesExplorer.MarkupReflection\ITypeResolver.cs' not found.
\2.0_rc7_src\Obfuscar\..\ilspy\ILSpy.BamlDecompiler\Ricciolo.StylesExplorer.MarkupReflection\KeyMapping.cs' not found.
\2.0_rc7_src\Obfuscar\..\ilspy\ILSpy.BamlDecompiler\Ricciolo.StylesExplorer.MarkupReflection\KnownInfo.cs' not found.
\2.0_rc7_src\Obfuscar\..\ilspy\ILSpy.BamlDecompiler\Ricciolo.StylesExplorer.MarkupReflection\NodesCollection.cs' not found.
\2.0_rc7_src\Obfuscar\..\ilspy\ILSpy.BamlDecompiler\Ricciolo.StylesExplorer.MarkupReflection\PropertyDeclaration.cs' not found.
\2.0_rc7_src\Obfuscar\..\ilspy\ILSpy.BamlDecompiler\Ricciolo.StylesExplorer.MarkupReflection\ResourceName.cs' not found.
\2.0_rc7_src\Obfuscar\..\ilspy\ILSpy.BamlDecompiler\Ricciolo.StylesExplorer.MarkupReflection\TypeDeclaration.cs' not found.
\2.0_rc7_src\Obfuscar\..\ilspy\ILSpy.BamlDecompiler\Ricciolo.StylesExplorer.MarkupReflection\XmlBamlElement.cs' not found.
\2.0_rc7_src\Obfuscar\..\ilspy\ILSpy.BamlDecompiler\Ricciolo.StylesExplorer.MarkupReflection\XmlBamlNode.cs' not found.
\2.0_rc7_src\Obfuscar\..\ilspy\ILSpy.BamlDecompiler\Ricciolo.StylesExplorer.MarkupReflection\XmlBamlProperty.cs' not found.
\2.0_rc7_src\Obfuscar\..\ilspy\ILSpy.BamlDecompiler\Ricciolo.StylesExplorer.MarkupReflection\XmlBamlPropertyElement.cs' not found.
\2.0_rc7_src\Obfuscar\..\ilspy\ILSpy.BamlDecompiler\Ricciolo.StylesExplorer.MarkupReflection\XmlBamlReader.cs' not found.
\2.0_rc7_src\Obfuscar\..\ilspy\ILSpy.BamlDecompiler\Ricciolo.StylesExplorer.MarkupReflection\XmlBamlSimpleProperty.cs' not found.
\2.0_rc7_src\Obfuscar\..\ilspy\ILSpy.BamlDecompiler\Ricciolo.StylesExplorer.MarkupReflection\XmlBamlText.cs' not found.
\2.0_rc7_src\Obfuscar\..\ilspy\ILSpy.BamlDecompiler\Ricciolo.StylesExplorer.MarkupReflection\XmlNamespace.cs' not found.
\2.0_rc7_src\Obfuscar\..\ilspy\ILSpy.BamlDecompiler\Ricciolo.StylesExplorer.MarkupReflection\XmlPIMapping.cs' not found.
```

And many more like those, plus others complaining that nuget it's not configured to install packages at compile time.

I'm using Visual Studio 2015 Community Edition Update 1.

**Comment by lextm** [comment]
You did not initialize the ILSpy sub module yet. Initialize that and the errors will go away.

**Comment by jjgh** [comment]
Well, there is no mention in that in the guide in either the basic example paragraph or configuration paragraph... and also I thought that the basic example was all set up to run..
What should I do exactly? I'm relatively new to .NET and C#.

**Comment by dedale** [comment]
Try running in your repo root folder :
`git submodule update --recursive`

**Comment by jjgh** [comment]
I needed it in a urgency so in the meantime I switched to DeepSea Obfuscator 4 (previously paid, but no longer updated and made free). If/when I will come back to obfuscar I will surely try given suggestion and give feedback here. Thank you!

**Comment by lextm** [comment]
Not sure if it would be better to change how the basic sample is shipped. I think of the following,

1. Write a script to download nuget.exe and Obfuscar NuGet package from NuGet.org.
1. Download some binaries from somewhere (Dropbox?).
1. Obfuscate the binaries.

That gets rid of the dependencies on MSBuild/Git, and should work more smoothly.

**Comment by lextm** [comment]
Simplified the sample project build process, https://github.com/lextm/obfuscar/tree/master/Examples/BasicExample/test.bat

**Comment by mailbee** [comment]
I'm having the same issue.

"You did not initialize the ILSpy sub module yet. Initialize that and the errors will go away." does not help, I don't understand how to do that "Initialize ILSpy submodule thing"..

**Comment by dedale** [comment]
@mailbee see my solution above

**Comment by mailbee** [comment]
C:\!Projects\obfuscar-master>git submodule update --recursive
fatal: Not a git repository (or any of the parent directories): .git

**Comment by dedale** [comment]
I don't understand why there is no .git folder in your got repo. Clone
failed?

**Comment by mailbee** [comment]
Thank you for your prompt and helpful replies. I repeated everything from the start and managed to get past the previous errors but now facing this when building .sln file within Visual Studio 2017 IDE:

`1>CoreCompile:
1>  C:\Program Files (x86)\MSBuild\14.0\bin\csc.exe /noconfig /nowarn:1701,1702,2008 /nostdlib+ /errorreport:prompt /warn:4 /define:DEBUG;TRACE /errorendlocation /preferreduilang:en-US /highentropyva- /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.0\Profile\Client\Microsoft.CSharp.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.0\Profile\Client\mscorlib.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.0\Profile\Client\PresentationCore.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.0\Profile\Client\System.Core.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.0\Profile\Client\System.Data.DataSetExtensions.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.0\Profile\Client\System.Data.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.0\Profile\Client\System.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.0\Profile\Client\System.Xml.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.0\Profile\Client\System.Xml.Linq.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.0\Profile\Client\WindowsBase.dll" /debug+ /debug:full /filealign:512 /optimize- /out:obj\Debug\Baml.dll /ruleset:"C:\Program Files (x86)\Microsoft Visual Studio 14.0\Team Tools\Static Analysis Tools\\Rule Sets\MinimumRecommendedRules.ruleset" /target:library /utf8output ..\ilspy\ILSpy.BamlDecompiler\CecilDependencyPropertyDescriptor.cs ..\ilspy\ILSpy.BamlDecompiler\CecilType.cs ..\ilspy\ILSpy.BamlDecompiler\CecilTypeResolver.cs ..\ilspy\ILSpy.BamlDecompiler\Ricciolo.StylesExplorer.MarkupReflection\BamlBinaryReader.cs ..\ilspy\ILSpy.BamlDecompiler\Ricciolo.StylesExplorer.MarkupReflection\BamlRecordType.cs ..\ilspy\ILSpy.BamlDecompiler\Ricciolo.StylesExplorer.MarkupReflection\IDependencyPropertyDescriptor.cs ..\ilspy\ILSpy.BamlDecompiler\Ricciolo.StylesExplorer.MarkupReflection\IType.cs ..\ilspy\ILSpy.BamlDecompiler\Ricciolo.StylesExplorer.MarkupReflection\ITypeResolver.cs ..\ilspy\ILSpy.BamlDecompiler\Ricciolo.StylesExplorer.MarkupReflection\KeyMapping.cs ..\ilspy\ILSpy.BamlDecompiler\Ricciolo.StylesExplorer.MarkupReflection\KnownInfo.cs ..\ilspy\ILSpy.BamlDecompiler\Ricciolo.StylesExplorer.MarkupReflection\NodesCollection.cs ..\ilspy\ILSpy.BamlDecompiler\Ricciolo.StylesExplorer.MarkupReflection\PropertyDeclaration.cs ..\ilspy\ILSpy.BamlDecompiler\Ricciolo.StylesExplorer.MarkupReflection\ResourceName.cs ..\ilspy\ILSpy.BamlDecompiler\Ricciolo.StylesExplorer.MarkupReflection\TypeDeclaration.cs ..\ilspy\ILSpy.BamlDecompiler\Ricciolo.StylesExplorer.MarkupReflection\XmlBamlElement.cs ..\ilspy\ILSpy.BamlDecompiler\Ricciolo.StylesExplorer.MarkupReflection\XmlBamlNode.cs ..\ilspy\ILSpy.BamlDecompiler\Ricciolo.StylesExplorer.MarkupReflection\XmlBamlProperty.cs ..\ilspy\ILSpy.BamlDecompiler\Ricciolo.StylesExplorer.MarkupReflection\XmlBamlPropertyElement.cs ..\ilspy\ILSpy.BamlDecompiler\Ricciolo.StylesExplorer.MarkupReflection\XmlBamlReader.cs ..\ilspy\ILSpy.BamlDecompiler\Ricciolo.StylesExplorer.MarkupReflection\XmlBamlSimpleProperty.cs ..\ilspy\ILSpy.BamlDecompiler\Ricciolo.StylesExplorer.MarkupReflection\XmlBamlText.cs ..\ilspy\ILSpy.BamlDecompiler\Ricciolo.StylesExplorer.MarkupReflection\XmlNamespace.cs ..\ilspy\ILSpy.BamlDecompiler\Ricciolo.StylesExplorer.MarkupReflection\XmlPIMapping.cs Helper.cs Properties\AssemblyInfo.cs "C:\Users\idh\AppData\Local\Temp\.NETFramework,Version=v4.0,Profile=Client.AssemblyAttributes.cs"
1>  Using shared compilation with compiler from directory: C:\Program Files (x86)\MSBuild\14.0\bin
1>C:\!Projects\obfuscar\ilspy\ILSpy.BamlDecompiler\CecilDependencyPropertyDescriptor.cs(8,7,8,11): error CS0246: The type or namespace name 'Mono' could not be found (are you missing a using directive or an assembly reference?)
1>C:\!Projects\obfuscar\ilspy\ILSpy.BamlDecompiler\CecilType.cs(7,7,7,11): error CS0246: The type or namespace name 'Mono' could not be found (are you missing a using directive or an assembly reference?)
1>C:\!Projects\obfuscar\ilspy\ILSpy.BamlDecompiler\CecilTypeResolver.cs(7,7,7,11): error CS0246: The type or namespace name 'Mono' could not be found (are you missing a using directive or an assembly reference?)
1>C:\!Projects\obfuscar\Baml\Helper.cs(1,7,1,11): error CS0246: The type or namespace name 'Mono' could not be found (are you missing a using directive or an assembly reference?)
1>C:\!Projects\obfuscar\Baml\Helper.cs(7,51,7,74): error CS0246: The type or namespace name 'InterfaceImplementation' could not be found (are you missing a using directive or an assembly reference?)
1>C:\!Projects\obfuscar\Baml\Helper.cs(7,23,7,37): error CS0246: The type or namespace name 'TypeDefinition' could not be found (are you missing a using directive or an assembly reference?)
1>C:\!Projects\obfuscar\ilspy\ILSpy.BamlDecompiler\CecilType.cs(14,21,14,35): error CS0246: The type or namespace name 'TypeDefinition' could not be found (are you missing a using directive or an assembly reference?)
1>C:\!Projects\obfuscar\ilspy\ILSpy.BamlDecompiler\CecilType.cs(16,20,16,34): error CS0246: The type or namespace name 'TypeDefinition' could not be found (are you missing a using directive or an assembly reference?)
1>C:\!Projects\obfuscar\ilspy\ILSpy.BamlDecompiler\CecilDependencyPropertyDescriptor.cs(16,3,16,17): error CS0246: The type or namespace name 'TypeDefinition' could not be found (are you missing a using directive or an assembly reference?)
1>C:\!Projects\obfuscar\ilspy\ILSpy.BamlDecompiler\CecilDependencyPropertyDescriptor.cs(18,59,18,73): error CS0246: The type or namespace name 'TypeDefinition' could not be found (are you missing a using directive or an assembly reference?)
1>C:\!Projects\obfuscar\ilspy\ILSpy.BamlDecompiler\CecilTypeResolver.cs(74,58,74,76): error CS0246: The type or namespace name 'AssemblyDefinition' could not be found (are you missing a using directive or an assembly reference?)
1>C:\!Projects\obfuscar\ilspy\ILSpy.BamlDecompiler\CecilTypeResolver.cs(74,3,74,17): error CS0246: The type or namespace name 'TypeDefinition' could not be found (are you missing a using directive or an assembly reference?)
1>C:\!Projects\obfuscar\ilspy\ILSpy.BamlDecompiler\CecilTypeResolver.cs(17,3,17,20): error CS0246: The type or namespace name 'IAssemblyResolver' could not be found (are you missing a using directive or an assembly reference?)
1>C:\!Projects\obfuscar\ilspy\ILSpy.BamlDecompiler\CecilTypeResolver.cs(18,3,18,21): error CS0246: The type or namespace name 'AssemblyDefinition' could not be found (are you missing a using directive or an assembly reference?)
1>C:\!Projects\obfuscar\ilspy\ILSpy.BamlDecompiler\CecilTypeResolver.cs(20,28,20,45): error CS0246: The type or namespace name 'IAssemblyResolver' could not be found (are you missing a using directive or an assembly reference?)
1>C:\!Projects\obfuscar\ilspy\ILSpy.BamlDecompiler\CecilTypeResolver.cs(20,56,20,74): error CS0246: The type or namespace name 'AssemblyDefinition' could not be found (are you missing a using directive or an assembly reference?)`

I was able to build via running build.debug and build.release files so perhaps that would be enough for me for the time being. But I guess it would be great if building .sln in the IDE should work either?

BTW, building in IDE fails with the same error even after successful building with .bat file. I initially thought maybe running .bat file will download/install the required deps so that IDE build will succeed then. However, my assumption was wrong.

**Comment by lextm** [comment]
The example has been moved to a separate repo and all related steps have been revised. Follow the new documentation and you should get it working,

http://docs.obfuscar.com/en/latest/tutorials/basics.html

**Comment by mailbee** [comment]
Thanks again. To the moment, I was able to run test.bat and all the tests have passed.
